import type { Metadata } from "next";
import { Geist, Geist_Mono, Arima, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Eneba App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} text-white bg-linear-to-b from-[#120338] to-[#1c0536] min-h-screen ${poppins.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
